class Campus {
  String name;
  String location;
  String imageAsset;
  String imageAsset2;
  String imageAsset3;
  String imageNetwork;
  String description;
  String openDays;
  String openTime;
  String accreditation;

  Campus({
    required this.name,
    required this.location,
    required this.imageNetwork,
    required this.imageAsset,
    required this.imageAsset2,
    required this.imageAsset3,
    required this.description,
    required this.openDays,
    required this.openTime,
    required this.accreditation,
  });
}

var campusList = [
  Campus(
    name: 'Institut Teknologi Sepuluh Nopember',
    location: 'Jl. Raya ITS, Keputih, Sukolilo, Surabaya, Jawa Timur 60111',
    imageNetwork: 'https://www.its.ac.id/news/wp-content/uploads/sites/2/2021/10/ITS-bertahan-pada-pemeringkatan-dunia-THE-WUR-by-Subjects-2022-dengan-tiga-subjek.jpeg',
    imageAsset: 'assets/images/its1.jpg',
    imageAsset2: 'assets/images/its3.jpeg',
    imageAsset3: 'assets/images/its2.jpg',
    description: 'Institut Teknologi Sepuluh Nopember (ITS) merupakan salah satu institusi pendidikan tinggi terkemuka di Indonesia yang fokus pada pengembangan ilmu pengetahuan dan teknologi. ITS memiliki beberapa fakultas yang mencakup berbagai disiplin ilmu, termasuk Fakultas Teknologi Industri, Fakultas Teknik Sipil dan Perencanaan, Fakultas Teknologi Kelautan, Fakultas Teknologi Elektro, Fakultas Matematika dan Ilmu Pengetahuan Alam, dan Fakultas Teknologi Informasi dan Komunikasi. ITS secara konsisten masuk dalam peringkat universitas terbaik di Indonesia dan memiliki reputasi baik di tingkat internasional dalam bidang teknik dan teknologi. Mahasiswa dan dosen ITS sering meraih penghargaan dalam berbagai kompetisi dan konferensi internasional. Kampus ITS juga dilengkapi dengan berbagai fasilitas modern termasuk laboratorium, perpustakaan, pusat penelitian, dan area hijau.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas Airlangga',
    location: 'Jl. Airlangga No.4 - 6, Airlangga, Gubeng, Surabaya, Jawa Timur 60115',
    imageNetwork: 'http://biaya.info/wp-content/uploads/2019/11/b271e-2.3-unair.jpg',
    imageAsset: 'assets/images/unair.jpg',
    imageAsset2: 'assets/images/unair2.jpg',
    imageAsset3: 'assets/images/unair3.jpg',
    description: 'Universitas Airlangga (UNAIR) adalah salah satu universitas negeri terkemuka di Indonesia yang memiliki berbagai program studi di bidang kedokteran, hukum, dan ilmu sosial. Universitas Airlangga (Unair) merupakan perguruan tinggi pertama di kawasan timur Indonesia yang didirikan pada tahun 1954. Perguruan Tinggi yang terletak di Surabaya, Jawa Timur ini diresmikan langsung oleh Presiden Soekarno bertepatan dengan hari pahlawan ke-9 yang jatuh pada tanggal 10 November 1954. Universitas Airlangga diresmikan setelah dua perguruan tinggi lainnya, yaitu Universitas Indonesia dan Universitas Gadjah Mada.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas Surabaya',
    location: 'Jl. Raya Kalirungkut, Kali Rungkut, Rungkut, Surabaya, Jawa Timur 60293',
    imageNetwork: 'https://i2.wp.com/harga.web.id/wp-content/uploads/Pintu-Utama-Kampus-ke-1-Universitas-Surabaya-Facebook-Universitas-Surabaya.jpg?resize=680%2C300&ssl=1',
    imageAsset: 'assets/images/ubaya.jpg',
    imageAsset2: 'assets/images/ubaya2.jpg',
    imageAsset3: 'assets/images/ubaya3.jpeg',
    description: 'Universitas Surabaya (UBAYA) adalah universitas swasta yang terkenal dengan program studi bisnis dan hukum. UBAYA bertujuan menghasilkan tenaga ahli dan ilmuwan, mengembangkan dan menyebarluaskan ilmu dan teknologi serta mengupayakan pengguna-annya untuk meningkatkan taraf hidup masyarakat, sesuai tuntutan masyarakat bisnis dan industri.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas Negeri Surabaya',
    location: 'Jl. Ketintang, Ketintang, Gayungan, Surabaya, Jawa Timur 60231',
    imageNetwork: 'https://asset.kompas.com/crops/qfzW0FWy64z1ChZ0v8jIbR8amck=/150x240:805x677/750x500/data/photo/2022/04/11/62543c8bbfc49.png',
    imageAsset: 'assets/images/unesa.png',
    imageAsset2: 'assets/images/unesa2.jpg',
    imageAsset3: 'assets/images/unesa3.jpg',
    description: 'Universitas Negeri Surabaya (UNESA) adalah salah satu universitas negeri yang berlokasi di Surabaya, Jawa Timur. Dikenal dengan fokus utamanya pada pendidikan dan keguruan, UNESA menawarkan berbagai program studi yang mencakup berbagai disiplin ilmu. Dengan komitmen untuk menghasilkan tenaga pendidik yang berkualitas dan profesional, UNESA menyediakan lingkungan belajar yang mendukung dan fasilitas yang memadai untuk menunjang proses belajar mengajar. Selain program pendidikan dan keguruan, UNESA juga memiliki program studi lain yang mencakup ilmu sosial, ilmu alam, serta seni dan olahraga. Universitas ini aktif dalam penelitian dan pengabdian kepada masyarakat, berkontribusi pada pengembangan ilmu pengetahuan dan kesejahteraan masyarakat. Dengan akreditasi unggul dan tenaga pengajar yang berpengalaman, UNESA menjadi pilihan yang tepat bagi para calon mahasiswa yang ingin meniti karir dalam bidang pendidikan maupun bidang lainnya.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas Katolik Widya Mandala',
    location: 'Jl. Dinoyo No.42-44, Keputran, Tegalsari, Surabaya, Jawa Timur 60265',
    imageNetwork: 'https://kompaspedia.kompas.id/wp-content/uploads/2020/08/foto_Universitas-Katolik-Widya-Mandala.jpg',
    imageAsset: 'assets/images/UKWM.jpg',
    imageAsset2: 'assets/images/UKWM2.jpg',
    imageAsset3: 'assets/images/UKWM3.jpeg',
    description: 'Universitas Katolik Widya Mandala (UKWMS) adalah salah satu universitas swasta terkemuka di Surabaya, Jawa Timur, yang memiliki reputasi kuat dalam menawarkan berbagai program studi berkualitas. Didirikan dengan nilai-nilai Katolik yang kuat, UKWMS berfokus pada pengembangan karakter dan moral mahasiswa, selain pendidikan akademis yang unggul. Universitas ini menyediakan berbagai program studi yang mencakup bidang-bidang seperti ekonomi, teknik, kedokteran, ilmu sosial, dan humaniora. Dengan fasilitas modern, laboratorium canggih, dan dosen yang berpengalaman, UKWMS memastikan bahwa para mahasiswanya mendapatkan pendidikan terbaik yang mempersiapkan mereka untuk tantangan profesional di masa depan. Selain itu, UKWMS juga mendorong keterlibatan dalam kegiatan ekstrakurikuler dan pengembangan soft skills, yang penting untuk pembentukan pribadi yang seimbang dan beretika. Dengan akreditasi Unggul (A), UKWMS terus berkomitmen untuk mencetak lulusan yang kompeten, berintegritas, dan siap berkontribusi positif bagi masyarakat.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Politeknik Elektronika Negeri Surabaya',
    location: 'Jl. Raya ITS, Keputih, Sukolilo, Surabaya, Jawa Timur 60111',
    imageNetwork: 'https://tse2.mm.bing.net/th?id=OIP.Aykmldb2MbDpWWmJ1ftBgwHaE8&pid=Api&P=0&h=180',
    imageAsset: 'assets/images/pens.jpg',
    imageAsset2: 'assets/images/pens2.png',
    imageAsset3: 'assets/images/pens3.jpg',
    description: 'Politeknik Elektronika Negeri Surabaya (PENS) adalah sebuah institusi pendidikan tinggi vokasi yang terletak di Surabaya, Jawa Timur, yang dikenal dengan keunggulannya dalam bidang elektronika dan teknologi informasi. Sebagai politeknik negeri, PENS menawarkan berbagai program studi yang dirancang untuk memberikan keterampilan praktis dan teknis yang dibutuhkan dalam industri modern. Dengan fokus pada pendidikan vokasi, PENS menyediakan lingkungan belajar yang menekankan pada pengalaman praktis, didukung oleh laboratorium yang dilengkapi dengan peralatan canggih dan fasilitas teknologi mutakhir. Mahasiswa di PENS mendapatkan kesempatan untuk terlibat dalam proyek-proyek nyata dan kerja sama dengan industri, yang mempersiapkan mereka secara optimal untuk memasuki dunia kerja. Selain itu, PENS juga dikenal dengan kegiatan penelitiannya yang inovatif dan kontribusi dalam pengembangan teknologi. Dengan staf pengajar yang berpengalaman dan kurikulum yang up-to-date, PENS terus berusaha mencetak lulusan yang kompeten, kreatif, dan siap berkontribusi dalam berbagai sektor industri. Akreditasi Unggul (A) yang dimiliki oleh PENS mencerminkan komitmen institusi ini terhadap kualitas pendidikan dan pengajaran yang tinggi.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Politeknik Perkapalan Negeri Surabaya',
    location: 'Jl. Teknik Kimia, Keputih, Sukolilo, Surabaya, Jawa Timur 60111',
    imageNetwork: 'https://i.ytimg.com/vi/-y8sMfta4HU/maxresdefault.jpg',
    imageAsset: 'assets/images/ppns.jpeg',
    imageAsset2: 'assets/images/ppns2.jpg',
    imageAsset3: 'assets/images/ppns3.png',
    description: 'Politeknik Perkapalan Negeri Surabaya (PPNS) adalah sebuah institusi pendidikan tinggi vokasi yang terletak di Surabaya, Jawa Timur, dan dikenal secara luas dengan keunggulannya dalam bidang perkapalan dan teknik kelautan. PPNS menawarkan program-program studi yang berfokus pada pengembangan keterampilan praktis dan pengetahuan teknis yang relevan dengan industri maritim dan perkapalan. Dengan fasilitas modern yang mencakup laboratorium, bengkel, dan simulator yang canggih, PPNS memastikan bahwa mahasiswa mendapatkan pelatihan yang komprehensif dan berkualitas tinggi. Kurikulum di PPNS dirancang untuk mencakup berbagai aspek teknik perkapalan, mulai dari desain dan konstruksi kapal hingga sistem propulsi dan manajemen pelabuhan. Selain itu, PPNS juga menjalin kerja sama yang erat dengan industri maritim dan perusahaan perkapalan, memberikan kesempatan kepada mahasiswa untuk mendapatkan pengalaman kerja nyata melalui program magang dan proyek kolaboratif. Dengan dosen yang berpengalaman dan ahli di bidangnya, PPNS berkomitmen untuk mencetak lulusan yang siap bersaing di pasar global. Akreditasi Unggul (A) yang dimiliki oleh PPNS mencerminkan kualitas pendidikan yang tinggi dan dedikasi institusi ini dalam memberikan pendidikan vokasi yang terbaik.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas 17 Agustus 1945 Surabaya',
    location: 'Jl. Semolowaru No.45, Menur Pumpungan, Sukolilo, Surabaya, Jawa Timur 60118',
    imageNetwork: 'https://tse4.mm.bing.net/th?id=OIP.SIIkhuvqJHLNboYmdbfJYAAAAA&pid=Api&P=0&h=180',
    imageAsset: 'assets/images/untag.jpg',
    imageAsset2: 'assets/images/untag2.jpeg',
    imageAsset3: 'assets/images/untag3.jpeg',
    description: 'Universitas 17 Agustus 1945 Surabaya (UNTAG) adalah salah satu universitas swasta terkemuka di Surabaya, Jawa Timur, yang telah berkomitmen untuk menyediakan pendidikan berkualitas bagi masyarakat Indonesia. Didirikan dengan semangat kemerdekaan dan nilai-nilai nasionalisme, UNTAG menawarkan berbagai program studi yang mencakup ilmu sosial, ilmu teknik, ilmu ekonomi, dan banyak lagi. Dengan kurikulum yang terus diperbarui dan disesuaikan dengan kebutuhan industri, UNTAG berfokus pada pengembangan kompetensi profesional dan keterampilan praktis mahasiswa, sehingga mereka siap untuk menghadapi tantangan dunia kerja. Universitas ini juga menyediakan berbagai fasilitas pendukung seperti perpustakaan, laboratorium, dan pusat kegiatan mahasiswa yang lengkap, untuk mendukung proses belajar mengajar yang efektif. Selain itu, UNTAG aktif dalam kegiatan penelitian dan pengabdian kepada masyarakat, memberikan kontribusi nyata bagi pembangunan sosial dan ekonomi. Dengan akreditasi Baik Sekali (B), UNTAG terus berupaya meningkatkan kualitas pendidikannya dan memastikan bahwa lulusannya memiliki daya saing yang tinggi di pasar global. Kampus yang ramah dan inklusif juga membuat UNTAG menjadi pilihan yang ideal bagi mahasiswa dari berbagai latar belakang.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Baik Sekali (B)',
  ),
  Campus(
    name: 'Universitas Ciputra',
    location: 'UC Town, Citraland, Made, Sambikerep, Surabaya, Jawa Timur 60219',
    imageNetwork: 'https://maukuliah.ap-south-1.linodeobjects.com/gallery/071071/Gedung%201%20UC.jpg',
    imageAsset: 'assets/images/uc.jpg',
    imageAsset2: 'assets/images/uc2.jpg',
    imageAsset3: 'assets/images/uc3.jpg',
    description: 'Universitas Ciputra (UC) adalah sebuah universitas swasta yang terletak di Surabaya, Jawa Timur, yang terkenal dengan fokusnya pada pendidikan kewirausahaan dan bisnis. Didirikan oleh pengusaha ternama Ciputra, universitas ini memiliki visi untuk menciptakan lulusan yang tidak hanya berpengetahuan luas, tetapi juga memiliki jiwa wirausaha yang kuat. Universitas Ciputra menawarkan berbagai program studi yang dirancang untuk mengembangkan kemampuan bisnis, inovasi, dan kreativitas mahasiswa. Fasilitas modern, kurikulum berbasis proyek, dan dukungan dari para profesional industri membuat pengalaman belajar di UC menjadi sangat relevan dan aplikatif. Mahasiswa diajak untuk terlibat langsung dalam berbagai proyek bisnis dan inkubator start-up, yang memberikan pengalaman nyata dalam mengelola bisnis dan mengembangkan ide-ide inovatif. Selain itu, UC juga menyediakan berbagai program pengembangan soft skills, seperti kepemimpinan, komunikasi, dan manajemen waktu, yang sangat penting untuk sukses dalam dunia bisnis. Dengan akreditasi Unggul (A), Universitas Ciputra memastikan bahwa kualitas pendidikan yang diberikan memenuhi standar nasional dan internasional, mempersiapkan lulusannya untuk menjadi pemimpin bisnis yang kompeten dan beretika.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas Muhammadiyah Surabaya',
    location: 'Jl. Sutorejo No.59, Dukuh Sutorejo, Mulyorejo, Surabaya, Jawa Timur 60113',
    imageNetwork: 'https://s3.ap-southeast-1.amazonaws.com/cdn.orbit/wp-content/uploads/2021/10/13171912/univ-2.jpg',
    imageAsset: 'assets/images/umsurabaya.jpg',
    imageAsset2: 'assets/images/umsurabaya2.jpg',
    imageAsset3: 'assets/images/umsurabaya3.jpg',
    description: 'Universitas Muhammadiyah Surabaya (UMSurabaya) adalah salah satu universitas swasta terkemuka di Surabaya, Jawa Timur, yang dikenal dengan pendekatan pendidikannya yang Islami dan komprehensif. Sebagai bagian dari jaringan perguruan tinggi Muhammadiyah, UMSurabaya berkomitmen untuk menyelenggarakan pendidikan yang berkualitas dengan mengintegrasikan nilai-nilai Islami dalam setiap aspek pembelajarannya. UMSurabaya menawarkan berbagai program studi yang mencakup bidang kesehatan, teknik, ilmu sosial, pendidikan, dan lain-lain, semuanya dirancang untuk memenuhi kebutuhan industri dan masyarakat. Dengan dukungan fasilitas modern, laboratorium yang lengkap, dan perpustakaan yang memadai, mahasiswa di UMSurabaya mendapatkan lingkungan belajar yang kondusif dan mendukung pengembangan akademik serta spiritual. Universitas ini juga aktif dalam penelitian dan pengabdian masyarakat, memberikan kontribusi nyata dalam pengembangan ilmu pengetahuan dan peningkatan kesejahteraan masyarakat. Melalui program-program ekstrakurikuler dan kegiatan kemahasiswaan yang beragam, UMSurabaya juga mendorong pengembangan soft skills seperti kepemimpinan, komunikasi, dan kerja tim. Akreditasi Unggul (A) yang dimiliki UMSurabaya mencerminkan dedikasi universitas ini dalam menjaga standar pendidikan yang tinggi dan menghasilkan lulusan yang kompeten serta berintegritas.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Universitas Kristen Petra',
    location: 'Jl. Siwalankerto No.121-131, Siwalankerto, Wonocolo, Surabaya, Jawa Timur 60236',
    imageNetwork: 'http://kuliahsambilkerja.info/wp-content/uploads/2019/10/Green_Building_UK_Petra-777x437.jpg',
    imageAsset: 'assets/images/petra.jpg',
    imageAsset2: 'assets/images/petra2.jpg',
    imageAsset3: 'assets/images/petra3.jpg',
    description: 'Universitas Kristen Petra (UK Petra) adalah salah satu universitas swasta terkemuka di Surabaya, Jawa Timur, yang memiliki reputasi unggul dalam berbagai program studi, terutama dalam bidang arsitektur dan desain interior. Didirikan dengan landasan nilai-nilai Kristen, UK Petra berkomitmen untuk menyediakan pendidikan yang holistik, menggabungkan pengembangan akademik dengan pembinaan karakter dan spiritualitas. Universitas ini menawarkan beragam program studi yang mencakup bidang teknik, bisnis, ilmu komunikasi, sastra, dan banyak lagi, semuanya dirancang untuk mempersiapkan mahasiswa menghadapi tantangan profesional di masa depan. UK Petra dilengkapi dengan fasilitas modern, termasuk laboratorium, studio desain, dan perpustakaan yang lengkap, untuk mendukung proses belajar mengajar yang efektif. Selain itu, universitas ini juga memiliki program internasional yang memungkinkan mahasiswa untuk mengikuti pertukaran pelajar dan program magang di luar negeri, memperluas wawasan dan pengalaman mereka. Kegiatan ekstrakurikuler yang beragam juga didorong untuk mengembangkan soft skills seperti kepemimpinan, kerja sama tim, dan kemampuan berkomunikasi. Dengan akreditasi Unggul (A), UK Petra terus berinovasi dalam metode pengajaran dan kurikulum untuk memastikan lulusannya siap berkontribusi positif dalam masyarakat dan dunia kerja.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
  Campus(
    name: 'Politeknik Kesehatan Kemenkes Surabaya',
    location: 'Jl. Pucang Jajar Tengah No.56, Pucang Sewu, Gubeng, Surabaya, Jawa Timur 60286',
    imageNetwork: 'https://tse2.mm.bing.net/th?id=OIP.fkDwdI69hmHSaWNsPtSshwHaEK&pid=Api&P=0&h=180',
    imageAsset: 'assets/images/poltekkes.jpg',
    imageAsset2: 'assets/images/poltekkes2.jpg',
    imageAsset3: 'assets/images/poltekkes3.jpg',
    description: 'Politeknik Kesehatan Kemenkes Surabaya (Poltekkes Kemenkes Surabaya) adalah institusi pendidikan tinggi vokasi yang berada di bawah naungan Kementerian Kesehatan Republik Indonesia. Terletak di Surabaya, Jawa Timur, Poltekkes ini dikenal dengan berbagai program studi kesehatan yang komprehensif dan aplikatif. Poltekkes Kemenkes Surabaya menawarkan program-program seperti keperawatan, kebidanan, teknologi laboratorium medis, kesehatan lingkungan, dan banyak lagi. Kurikulum yang diterapkan di Poltekkes ini dirancang untuk memberikan keseimbangan antara teori dan praktik, memastikan bahwa mahasiswa mendapatkan pengetahuan mendalam sekaligus keterampilan praktis yang dibutuhkan dalam dunia kerja kesehatan. Dengan fasilitas lengkap yang mencakup laboratorium modern, rumah sakit pendidikan, dan pusat simulasi medis, mahasiswa Poltekkes Kemenkes Surabaya dapat mengasah keterampilan klinis mereka secara maksimal. Selain itu, Poltekkes ini juga berfokus pada pengembangan soft skills seperti komunikasi efektif, etika profesi, dan manajemen kesehatan. Melalui berbagai program magang dan kerja sama dengan rumah sakit serta instansi kesehatan lainnya, mahasiswa mendapatkan kesempatan untuk terjun langsung ke lapangan dan menghadapi situasi nyata dalam pelayanan kesehatan. Akreditasi Baik Sekali (B) yang dimiliki Poltekkes Kemenkes Surabaya mencerminkan komitmen institusi ini untuk terus meningkatkan kualitas pendidikan dan menghasilkan tenaga kesehatan yang profesional dan kompeten.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Baik Sekali (B)',
  ),
  Campus(
    name: 'Sekolah Tinggi Teknik Surabaya (STTS)',
    location: 'Jl. Ngagel Jaya Tengah No.73-77, Ngagelrejo, Wonokromo, Surabaya, Jawa Timur 60283',
    imageNetwork: 'https://4.bp.blogspot.com/-aXOqJ_GvM_U/WaIhJagN9DI/AAAAAAAAGIs/vUNwpy8W-UoxFM-GEoawvxQ31IY6tNsAgCLcBGAs/s1600/Daftar%2BJurusan%2Bdan%2BProgram%2BStudi%2BSTTS%2BSekolah%2BTinggi%2BTeknik%2BSurabaya.png',
    imageAsset: 'assets/images/stts.jpg',
    imageAsset2: 'assets/images/stts2.jpg',
    imageAsset3: 'assets/images/stts3.jpg',
    description: 'Sekolah Tinggi Teknik Surabaya (STTS) adalah institusi pendidikan tinggi swasta yang berlokasi di Surabaya, Jawa Timur, yang dikenal dengan fokusnya pada pendidikan teknik dan teknologi informasi. STTS menawarkan berbagai program studi yang dirancang untuk memenuhi kebutuhan industri modern, termasuk teknik elektro, teknik informatika, teknik komputer, dan sistem informasi. Kurikulum di STTS menggabungkan teori mendalam dengan praktik intensif, memungkinkan mahasiswa untuk mengembangkan pengetahuan teknis yang kuat serta keterampilan praktis yang dibutuhkan di dunia kerja. Fasilitas modern, seperti laboratorium komputer, laboratorium jaringan, dan pusat penelitian, mendukung proses belajar yang efektif dan inovatif. STTS juga menekankan pengembangan soft skills, seperti kemampuan berkomunikasi, kepemimpinan, dan kerja tim, yang sangat penting dalam dunia profesional. Selain itu, STTS memiliki berbagai program kerja sama dengan industri dan perusahaan teknologi, memberikan mahasiswa kesempatan untuk magang dan terlibat dalam proyek-proyek nyata yang relevan dengan bidang studi mereka. Dengan akreditasi Unggul (A), STTS berkomitmen untuk terus meningkatkan kualitas pendidikan dan memastikan bahwa lulusannya siap bersaing dan berkontribusi dalam industri teknologi yang terus berkembang.',
    openDays: 'Senin - Jumat',
    openTime: '08:00 - 16:00',
    accreditation: 'Unggul (A)',
  ),
];
